In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

# COLLISION

In [ ]:
col = pd.read_csv("collision.csv")
col_clean = col.copy()
col_clean.columns

Index(['collision_index', 'collision_year', 'collision_ref_no',
       'location_easting_osgr', 'location_northing_osgr', 'longitude',
       'latitude', 'police_force', 'collision_severity', 'number_of_vehicles',
       'number_of_casualties', 'date', 'day_of_week', 'time',
       'local_authority_district', 'local_authority_ons_district',
       'local_authority_highway', 'local_authority_highway_current',
       'first_road_class', 'first_road_number', 'road_type', 'speed_limit',
       'junction_detail_historic', 'junction_detail', 'junction_control',
       'second_road_class', 'second_road_number',
       'pedestrian_crossing_human_control_historic',
       'pedestrian_crossing_physical_facilities_historic',
       'pedestrian_crossing', 'light_conditions', 'weather_conditions',
       'road_surface_conditions', 'special_conditions_at_site',
       'carriageway_hazards_historic', 'carriageway_hazards',
       'urban_or_rural_area', 'did_police_officer_attend_scene_of_accident',
       'trunk_road_flag', 'lsoa_of_accident_location',
       'enhanced_severity_collision', 'collision_injury_based',
       'collision_adjusted_severity_serious',
       'collision_adjusted_severity_slight'],
      dtype='str')

In [29]:
collision_drop = [                                                                                                                                                                                                                                                          
    "collision_year", "collision_ref_no", "location_easting_osgr",
    "location_northing_osgr", "police_force", "local_authority_district",                                                                                                                                                                                                   
    "local_authority_ons_district", "local_authority_highway",
    "local_authority_highway_current", "second_road_class", "second_road_number",                                                                                                                                                                                           
    "junction_detail_historic", "pedestrian_crossing_human_control_historic",
    "pedestrian_crossing_physical_facilities_historic", "carriageway_hazards_historic",                                                                                                                                                                                     
    "trunk_road_flag", "did_police_officer_attend_scene_of_accident",                                                                                                                                                                                                       
    "lsoa_of_accident_location", "enhanced_severity_collision",
    "collision_injury_based", "collision_adjusted_severity_serious",                                                                                                                                                                                                        
    "collision_adjusted_severity_slight"                                                                                                                                                                                                                                    
]

col_clean = col.drop(columns=collision_drop)
col_clean.head()

,collision_index,longitude,latitude,collision_severity,number_of_vehicles,number_of_casualties,date,day_of_week,time,first_road_class,...,speed_limit,junction_detail,junction_control,pedestrian_crossing,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area
0,2021170H10421,-1.270905,54.689833,3,2,2,22/05/2021,7,22:44,6,...,60,0,-1,0,6,1,1,0,0,2
1,2021170H11231,-1.218333,54.690592,3,2,1,20/10/2021,4,15:50,4,...,30,16,2,0,1,1,1,0,0,1
2,2020170M11750,-1.232884,54.570397,3,2,1,01/12/2020,3,18:00,6,...,20,16,4,0,4,1,1,0,0,1
3,2021170M31761,-1.233040,54.520825,3,1,1,09/12/2021,5,16:55,5,...,40,0,-1,0,4,1,2,0,0,2
4,2021170S10441,-1.290292,54.580641,3,3,1,12/04/2021,2,09:02,3,...,70,0,-1,0,1,1,1,4,13,2

# VEHICLE

In [24]:
veh = pd.read_csv("vehicle.csv")
veh_clean = veh.copy()
veh_clean.columns

/tmp/ipykernel_10715/2890025682.py:1: DtypeWarning: Columns (0: generic_make_model) have mixed types. Specify dtype option on import or set low_memory=False.
  veh = pd.read_csv("vehicle.csv")

Index(['collision_index', 'collision_year', 'collision_ref_no',
       'vehicle_reference', 'vehicle_type', 'towing_and_articulation',
       'vehicle_manoeuvre_historic', 'vehicle_manoeuvre',
       'vehicle_direction_from', 'vehicle_direction_to',
       'vehicle_location_restricted_lane_historic',
       'vehicle_location_restricted_lane', 'junction_location',
       'skidding_and_overturning', 'hit_object_in_carriageway',
       'vehicle_leaving_carriageway', 'hit_object_off_carriageway',
       'first_point_of_impact', 'vehicle_left_hand_drive',
       'journey_purpose_of_driver_historic', 'journey_purpose_of_driver',
       'sex_of_driver', 'age_of_driver', 'age_band_of_driver',
       'engine_capacity_cc', 'propulsion_code', 'age_of_vehicle',
       'generic_make_model', 'driver_imd_decile', 'lsoa_of_driver',
       'escooter_flag', 'driver_distance_banding'],
      dtype='str')

In [30]:
vehicle_drop = [
      "collision_year", "collision_ref_no", "vehicle_manoeuvre_historic",
      "vehicle_location_restricted_lane_historic", "journey_purpose_of_driver_historic",                                                                                                                                                                                      
      "vehicle_direction_from", "vehicle_direction_to", "age_band_of_driver",
      "vehicle_left_hand_drive", "lsoa_of_driver", "escooter_flag"                                                                                                                                                                                                            
  ] 

veh_clean = veh.drop(columns=vehicle_drop) 
veh_clean.head()

,collision_index,vehicle_reference,vehicle_type,towing_and_articulation,vehicle_manoeuvre,vehicle_location_restricted_lane,junction_location,skidding_and_overturning,hit_object_in_carriageway,vehicle_leaving_carriageway,...,first_point_of_impact,journey_purpose_of_driver,sex_of_driver,age_of_driver,engine_capacity_cc,propulsion_code,age_of_vehicle,generic_make_model,driver_imd_decile,driver_distance_banding
0,2020210979534,2,5,0,3,0,0,0,0,0,...,2,6,1,57,798,1,4,BMW F 800,3,-1
1,2020030959800,1,5,0,19,0,0,0,0,1,...,1,6,1,59,798,1,3,BMW F 800,6,-1
2,2020360978858,2,5,0,19,0,0,5,0,0,...,1,2,1,64,798,1,11,BMW F 800,4,-1
3,2020430340711,1,5,0,19,0,0,0,0,7,...,1,6,1,48,798,1,8,BMW F 800,8,-1
4,2020010260297,1,5,0,99,99,0,9,99,9,...,9,2,1,36,798,1,9,BMW F 800,8,-1

# CASUALTY

In [27]:
cas = pd.read_csv("casualty.csv")
cas_clean = cas.copy()
cas_clean.columns

Index(['collision_index', 'collision_year', 'collision_ref_no',
       'vehicle_reference', 'casualty_reference', 'casualty_class',
       'sex_of_casualty', 'age_of_casualty', 'age_band_of_casualty',
       'casualty_severity', 'pedestrian_location', 'pedestrian_movement',
       'car_passenger', 'bus_or_coach_passenger',
       'pedestrian_road_maintenance_worker', 'casualty_type',
       'casualty_imd_decile', 'lsoa_of_casualty', 'enhanced_casualty_severity',
       'casualty_injury_based', 'casualty_adjusted_severity_serious',
       'casualty_adjusted_severity_slight', 'casualty_distance_banding'],
      dtype='str')

In [31]:
casualty_drop = [
      "collision_year", "collision_ref_no", "age_band_of_casualty",
      "casualty_distance_banding", "pedestrian_road_maintenance_worker",                                                                                                                                                                                                      
      "lsoa_of_casualty", "enhanced_casualty_severity", "casualty_injury_based",
      "casualty_adjusted_severity_serious", "casualty_adjusted_severity_slight"                                                                                                                                                                                               
  ]               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
cas_clean = cas.drop(columns=casualty_drop)
cas_clean.head()

,collision_index,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,casualty_severity,pedestrian_location,pedestrian_movement,car_passenger,bus_or_coach_passenger,casualty_type,casualty_imd_decile
0,2020010280094,1,1,3,2,24,3,8,9,0,0,0,3
1,202031D109620,1,1,3,2,95,2,5,1,0,0,0,6
2,2020401003715,1,1,3,1,39,3,5,1,0,0,0,2
3,2021201086330,1,1,3,1,63,3,6,9,0,0,0,3
4,2021371050963,1,1,3,1,51,3,9,9,0,0,0,9